"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { BookOpenCheck, ClipboardList, GraduationCap, Inbox, LayoutDashboard, LogOut, Send, UserRoundCog, UsersRound } from "lucide-react";
import type { SessionUser } from "@/lib/types";

const adminNav=[{href:"/admin",label:"College overview",icon:LayoutDashboard},{href:"/admin/students",label:"Students",icon:GraduationCap},{href:"/admin/professors",label:"Professors",icon:UsersRound},{href:"/admin/courses",label:"Subjects",icon:BookOpenCheck},{href:"/admin/assignments",label:"Subject assignments",icon:UserRoundCog},{href:"/admin/assessments",label:"Internal tests",icon:ClipboardList},{href:"/admin/submissions",label:"Admin inbox",icon:Inbox},{href:"/admin/university",label:"University email",icon:Send}];
const professorNav=[{href:"/professor",label:"Capture overview",icon:LayoutDashboard},{href:"/professor/courses",label:"My subjects",icon:BookOpenCheck},{href:"/professor/submissions",label:"Submit to Admin",icon:Send}];
const studentNav=[{href:"/student",label:"Overview",icon:LayoutDashboard}];
export function AppShell({user,children}:{user:SessionUser;children:React.ReactNode}){const path=usePathname();const router=useRouter();const nav=user.user_type==="ADMIN"?adminNav:user.user_type==="PROFESSOR"?professorNav:studentNav;async function logout(){await fetch("/api/auth/logout",{method:"POST"});router.push("/login");router.refresh();}return <div className="app-shell"><aside className="sidebar"><div className="sidebar-brand"><div className="brand-mark small"><GraduationCap/></div><div><strong>VCEW Results</strong><span>Regulation 2023</span></div></div><nav aria-label="Main navigation">{nav.map(item=>{const Icon=item.icon;const active=path===item.href;return <Link key={item.href} href={item.href} className={active?"nav-link active":"nav-link"}><Icon/>{item.label}</Link>})}</nav><button className="nav-link logout" onClick={logout}><LogOut/>Sign out</button></aside><div className="app-main"><header className="topbar"><div><span className="mobile-brand">VCEW Results</span></div><div className="user-chip"><span>{user.username.slice(0,2)}</span><div><strong>{user.username}</strong><small>{user.user_type.toLowerCase()}</small></div></div></header><main className="page-content">{children}</main></div></div>}
