"""add marksheet uploads

Revision ID: 148b7ff50258
Revises: cbe966df5417
Create Date: 2026-08-27 10:39:32.389281
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '148b7ff50258'
down_revision: Union[str, None] = 'cbe966df5417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marksheet_uploads',
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('assessment_id', sa.Uuid(), nullable=False),
    sa.Column('course_offering_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('capture_quality_json', sa.JSON(), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('client_request_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['course_offering_id'], ['course_offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_request_id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_marksheet_uploads_assessment_id'), 'marksheet_uploads', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_marksheet_uploads_checksum_sha256'), 'marksheet_uploads', ['checksum_sha256'], unique=True)
    op.create_index(op.f('ix_marksheet_uploads_course_offering_id'), 'marksheet_uploads', ['course_offering_id'], unique=False)
    op.create_index(op.f('ix_marksheet_uploads_student_id'), 'marksheet_uploads', ['student_id'], unique=False)
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marksheet_uploads_student_id'), table_name='marksheet_uploads')
    op.drop_index(op.f('ix_marksheet_uploads_course_offering_id'), table_name='marksheet_uploads')
    op.drop_index(op.f('ix_marksheet_uploads_checksum_sha256'), table_name='marksheet_uploads')
    op.drop_index(op.f('ix_marksheet_uploads_assessment_id'), table_name='marksheet_uploads')
    op.drop_table('marksheet_uploads')
    # ### end Alembic commands ###
