"""add ocr review workflow

Revision ID: 871009b0e5c1
Revises: 148b7ff50258
Create Date: 2026-08-28 09:45:13.556667
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '871009b0e5c1'
down_revision: Union[str, None] = '148b7ff50258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_extractions',
    sa.Column('marksheet_upload_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_text', sa.String(length=100), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('bounding_box_json', sa.JSON(), nullable=False),
    sa.Column('recognizer_version', sa.String(length=255), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('reviewed_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['marksheet_upload_id'], ['marksheet_uploads.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marksheet_upload_id', 'field_name')
    )
    op.create_index(op.f('ix_ocr_extractions_marksheet_upload_id'), 'ocr_extractions', ['marksheet_upload_id'], unique=False)
    op.create_table('ocr_jobs',
    sa.Column('marksheet_upload_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('recognizer_version', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['marksheet_upload_id'], ['marksheet_uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marksheet_upload_id')
    )
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_jobs')
    op.drop_index(op.f('ix_ocr_extractions_marksheet_upload_id'), table_name='ocr_extractions')
    op.drop_table('ocr_extractions')
    # ### end Alembic commands ###
